/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScrapeRouteImport } from './routes/scrape'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfluencersIndexRouteImport } from './routes/influencers/index'
import { Route as InfluencersIdRouteImport } from './routes/influencers/$id'

const ScrapeRoute = ScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersIndexRoute = InfluencersIndexRouteImport.update({
  id: '/influencers/',
  path: '/influencers/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencersIdRoute = InfluencersIdRouteImport.update({
  id: '/influencers/$id',
  path: '/influencers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/scrape': typeof ScrapeRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/influencers': typeof InfluencersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/scrape': typeof ScrapeRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/influencers': typeof InfluencersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/scrape': typeof ScrapeRoute
  '/influencers/$id': typeof InfluencersIdRoute
  '/influencers/': typeof InfluencersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/scrape'
    | '/influencers/$id'
    | '/influencers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/scrape'
    | '/influencers/$id'
    | '/influencers'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/scrape'
    | '/influencers/$id'
    | '/influencers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ScrapeRoute: typeof ScrapeRoute
  InfluencersIdRoute: typeof InfluencersIdRoute
  InfluencersIndexRoute: typeof InfluencersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scrape': {
      id: '/scrape'
      path: '/scrape'
      fullPath: '/scrape'
      preLoaderRoute: typeof ScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/': {
      id: '/influencers/'
      path: '/influencers'
      fullPath: '/influencers'
      preLoaderRoute: typeof InfluencersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencers/$id': {
      id: '/influencers/$id'
      path: '/influencers/$id'
      fullPath: '/influencers/$id'
      preLoaderRoute: typeof InfluencersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ScrapeRoute: ScrapeRoute,
  InfluencersIdRoute: InfluencersIdRoute,
  InfluencersIndexRoute: InfluencersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
